### ISSUE TITLE
chuangzhi你真的有点过分了

### ISSUE THREAD

**Issue by code004Accepted** [chuang-zhi/Luogu-On-VS-Code#3]
1. 自己项目确实很垃圾，然后呢？还说“抢了yltx的饭碗”，我问问你有资格吗？自己看下载量
2. 自己刷下载量并强迫我帮你刷下载量，我问问你有脸吗？
3. 盗我的号。我问问你为啥之前我的几个洛谷小号封禁原因都是“chuangzhi小号”啊？洛谷管理员是瞎子吗？我当时确实没有怀疑，但这样看来肯定就是你盗的咯
4. 自己盗自己号，自己演戏，还说是我盗你的号，有没有脸啊...
5. 到现在，还用Coderhub的名义发布产品，我问问你有权力吗？Coderhub自从当初你退出开始，已经归“硅谷小蛙”管了，你现在用Coderhub的名义发布，属于侵权行为，至少你必须先得到硅谷小蛙的认可

我不跟你扯其他的，请你先把上面的所谓“巧合”解释清楚，否则我会联系网警。

哦不对，我好像已经联系了，那就等网警敲你家门咯~

当然了，给解释永远都不晚（

**Comment by chuang-zhi** [comment]
感谢您提的Issues。

1.第一件事我不发表任何言论，下载量是少，但是我相信做的好就一定有人用


2.我并没有强迫，反倒是您在恶意刷一星，如果我强迫你了，请给出证据


3.洛谷判断小号是根据Cookies里面的__client_id_来判断的，所以应该是按照__client_id_判断是否为小号——既然如此，那么登陆两次账号就可以被判为client id相同


4.同上，我zz啊，监守自盗？


5.Coderhub注册了商标吗？如果没有，那么这个名字在法律上是不被承认的


6.您联系了网警？请提供立案证明，谢谢！


祝好，
Jobs Au




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Brian Chen"<notifications@github.com&gt;; 
发送时间: 2020年6月21日(星期天) 晚上10:26
收件人: "chuang-zhi/Luogu-On-VS-Code"<Luogu-On-VS-Code@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3)





  
自己项目确实很垃圾，然后呢？还说“抢了yltx的饭碗”，我问问你有资格吗？自己看下载量
 
自己刷下载量并强迫我帮你刷下载量，我问问你有脸吗？
 
盗我的号。我问问你为啥之前我的几个洛谷小号封禁原因都是“chuangzhi小号”啊？洛谷管理员是瞎子吗？我当时确实没有怀疑，但这样看来肯定就是你盗的咯
 
自己盗自己号，自己演戏，还说是我盗你的号，有没有脸啊...
 
到现在，还用Coderhub的名义发布产品，我问问你有权力吗？Coderhub自从当初你退出开始，已经归“硅谷小蛙”管了，你现在用Coderhub的名义发布，属于侵权行为，至少你必须先得到硅谷小蛙的认可
  
我不跟你扯其他的，请你先把上面的所谓“巧合”解释清楚，否则我会联系网警。
 
哦不对，我好像已经联系了，那就等网警敲你家门咯~
 
当然了，给解释永远都不晚（

**Comment by code004Accepted** [comment]
你还没自杀呢，不涉及刑事案件，存在个鬼的立案证明

要立案，你先把你之前说的要自杀实现了就成

**Comment by code004Accepted** [comment]
此外，我只打了一个一星，而且那是我的真实评价，所以说您做的东西我觉得不满意了打个差评都叫“刷”？就评价了一次

**Comment by code004Accepted** [comment]
其次，您做的根本不好，不要跟我扯什么“做的好就一定有人用”，反正现在很少人用是事实摆在这里

**Comment by code004Accepted** [comment]
众所周知的事情是洛谷存储了所有登录的IP记录

那我问问您啊，为啥洛谷管理员在所有事件中都知道使用账号的人是否是账号主人呢？而且也知道账号的大小号关系

还有，您自己盗号不叫监守自盗...您分明就是演戏演给所有人看，哗众取宠。现在全部被我查出来了，就开始抵赖了。佩服佩服，您说谎都不脸红的是吧

哦对了，我好像不太清楚屏幕那边的您脸红了没有呢

**Comment by code004Accepted** [comment]
至于您的话，总之您不来骚扰我我是不会搭理您的，但是如果您继续骚扰我，对不起，我是不可能饶了您的

毕竟您也给我造成了相当巨大的心理损失与经济损失

根据昨晚我联系的在线免费律师，您需要赔偿的损失在五千元到三万元之间

![screenshot.png](https://i.loli.net/2020/06/22/9k2aUeodfbtCYGL.png)

**Comment by code004Accepted** [comment]
然后呢，还在继续刷下载量是吧

昨天下载量60多，今天就80了，你以为我是傻子吗...

![image](https://user-images.githubusercontent.com/36566134/85290380-786d2100-b4cb-11ea-97df-69e6886b6f35.png)

不得不说，我还是非常佩服chuangzhi（Jobs Au）的，能这么脸皮厚的人我也是没见过了

**Comment by code004Accepted** [comment]
哦还有，您说得对，您盗自己的号的确是zz行为，您以为演戏还能让别人心动、同情您？？？

不可能的，给👴爪巴

**Comment by chuang-zhi** [comment]
奇奇怪怪，不是说通知网警了吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Brian Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 晚上8:30
收件人:&nbsp;"chuang-zhi/Luogu-On-VS-Code"<Luogu-On-VS-Code@noreply.github.com&gt;;
抄送:&nbsp;"BabyQ"<2869237730@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3)





 
你还没自杀呢，不是刑事案件，存在个鬼的立案证明
 
要立案，你先把你之前说的要自杀实现了就成

**Comment by chuang-zhi** [comment]
真就一次，hh


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Brian Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 晚上8:31
收件人:&nbsp;"chuang-zhi/Luogu-On-VS-Code"<Luogu-On-VS-Code@noreply.github.com&gt;;
抄送:&nbsp;"BabyQ"<2869237730@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3)





 
此外，我只打了一个一星，而且那是我的真实评价，所以说您做的东西我觉得不满意了打个差评都叫“刷”？就评价了一次

**Comment by chuang-zhi** [comment]
谁都像您这么想，那马化腾就不用造QQ了，直接用ICQ不好吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Brian Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 晚上8:32
收件人:&nbsp;"chuang-zhi/Luogu-On-VS-Code"<Luogu-On-VS-Code@noreply.github.com&gt;;
抄送:&nbsp;"BabyQ"<2869237730@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3)





 
其次，您做的根本不好，不要跟我扯什么“做的好就一定有人用”，反正现在很少人用是事实摆在这里

**Comment by chuang-zhi** [comment]
好呀，我可以向luogu申请查IP


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Brian Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 晚上8:41
收件人:&nbsp;"chuang-zhi/Luogu-On-VS-Code"<Luogu-On-VS-Code@noreply.github.com&gt;;
抄送:&nbsp;"BabyQ"<2869237730@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3)





 
众所周知的事情是洛谷存储了所有登录的IP记录
 
那我问问您啊，为啥洛谷管理员在所有事件中都知道使用账号的人是否是账号主人呢？而且也知道账号的大小号关系
 
还有，您自己盗号不叫监守自盗...您分明就是演戏演给所有人看，哗众取宠。现在全部被我查出来了，就开始抵赖了。佩服佩服，您说谎都不脸红的是吧
 
哦对了，我好像不太清楚屏幕那边的您脸红了没有呢

**Comment by chuang-zhi** [comment]
我并没有骚扰您呢，倒是有人使用Tidio给我发信息骚扰我呢……如果有聊天记录，请截图


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Brian Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 晚上8:51
收件人:&nbsp;"chuang-zhi/Luogu-On-VS-Code"<Luogu-On-VS-Code@noreply.github.com&gt;;
抄送:&nbsp;"BabyQ"<2869237730@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3)





 
至于您的话，总之您不来骚扰我我是不会搭理您的，但是如果您继续骚扰我，对不起，我是不可能饶了您的
 
毕竟您也给我造成了相当巨大的心理损失与经济损失
 
根据昨晚我联系的在线免费律师，您需要赔偿的损失在五千元到三万元之间

**Comment by chuang-zhi** [comment]
随您吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "code004Accepted"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 晚上9:02
收件人: "chuang-zhi/Luogu-On-VS-Code"<Luogu-On-VS-Code@noreply.github.com&gt;; 
抄送: "BabyQ"<2869237730@qq.com&gt;; "chuang-zhi/comment"<comment@noreply.github.com&gt;; 
主题: Re: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3)





 
哦还有，您说得对，您盗自己的号的确是zz行为，您以为演戏还能让别人心动、同情您？？？
 
不可能的，给👴爪巴
 
&mdash;

**Comment by chuang-zhi** [comment]
我并没有刷下载量，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"code004Accepted"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 晚上9:01
收件人:&nbsp;"chuang-zhi/Luogu-On-VS-Code"<Luogu-On-VS-Code@noreply.github.com&gt;;
抄送:&nbsp;"BabyQ"<2869237730@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3)





 
然后呢，还在继续刷下载量是吧
 
昨天下载量60多，今天就80了，你以为我是傻子吗...
 

 
不得不说，我还是非常佩服chuangzhi（Jobs Au）的，能脸皮这么厚的人我也是没见过了

**Comment by xu-shawn** [comment]
IEE

**Comment by code004Accepted** [comment]
懒得跟您瞎BB，就算有第三者来盗了我们的号，您也必须因为您对我所做出的行为进行道歉

既然您没有任何办法证明不是您盗的号，而且基本所有谷民都知道您之前的所作所为（并从中可以直接得出您是一个XXS的结论），我也就不多说什么了

SB XXS滚吧

**Comment by code004Accepted** [comment]
> 奇奇怪怪，不是说通知网警了吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Brian Chen"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月22日(星期一) 晚上8:30 收件人:&nbsp;"chuang-zhi/Luogu-On-VS-Code"<Luogu-On-VS-Code@noreply.github.com&gt;; 抄送:&nbsp;"BabyQ"<2869237730@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3) 你还没自杀呢，不是刑事案件，存在个鬼的立案证明 要立案，你先把你之前说的要自杀实现了就成 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

您tm是真傻还是装傻？我还tm说得不够清楚？？？您盗我号充其量只是个民事纠纷，要想要立案证明，您之前不是用跳楼来威胁我们所有成员吗？您跳下去了，我就可以拿到立案证明了。等您父母给我死亡证明，我就马上联系派出所立案，然后我会尽快把立案证明发给您，哦不，发给您现在所持有的账号的。

连话都tm听不懂，劝你别搞OI这行了，也别搞啥SB项目了，滚粗吧

**Comment by chuang-zhi** [comment]
> > 奇奇怪怪，不是说通知网警了吗
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Brian Chen"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年6月22日(星期一) 晚上8:30 收件人: "chuang-zhi/Luogu-On-VS-Code"<[Luogu-On-VS-Code@noreply.github.com](mailto:Luogu-On-VS-Code@noreply.github.com)>; 抄送: "BabyQ"<[2869237730@qq.com](mailto:2869237730@qq.com)>;"Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3) 你还没自杀呢，不是刑事案件，存在个鬼的立案证明 要立案，你先把你之前说的要自杀实现了就成 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 您tm是真傻还是装傻？我还tm说得不够清楚？？？您盗我号充其量只是个民事纠纷，要想要立案证明，您之前不是用跳楼来威胁我们所有成员吗？您跳下去了，我就可以拿到立案证明了。等您父母给我死亡证明，我就马上联系派出所立案，然后我会尽快把立案证明发给您，哦不，发给您现在所持有的账号的。
> 
> 连话都tm听不懂，劝你别搞OI这行了，也别搞啥SB项目了，滚粗吧

随你吧

**Comment by chuang-zhi** [comment]
我没有抹黑你啊……

**Comment by williamlyz666** [comment]
我谔谔

**Comment by luosiwei-cmd** [comment]
我谔谔

**Comment by chuang-zhi** [comment]
捕捉luosw
---原始邮件---
发件人:&quot;luosiwei-cmd&quot;<notifications@github.com&gt;
发送时间:2020年6月25日 星期四 下午10:35
收件人:&quot;chuang-zhi/Luogu-On-VS-Code&quot;<Luogu-On-VS-Code@noreply.github.com&gt;
抄送:&quot;Jobs Au&quot;<2869237730@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;
主题:Re: [chuang-zhi/Luogu-On-VS-Code] chuangzhi你真的有点过分了 (#3)



我谔谔

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by Wowing** [comment]
IEE

**Comment by xu-shawn** [comment]
考古

**Comment by zhanglinquan** [comment]
吃瓜，都闹了多久了啊？！

**Comment by zhanglinquan** [comment]
吃瓜，都闹了多久了啊？！

**Comment by qz-cqy** [comment]
考古

**Comment by jwjawa** [comment]
考古

**Comment by TNTtian** [comment]
考古

**Comment by zxp2019** [comment]
考古

**Comment by AMIRIOX** [comment]
考古 什么梗啊
