### ISSUE TITLE
麻烦您将本扩展下架并删除

### ISSUE THREAD

**Issue by yltx** [chuang-zhi/Luogu-On-VS-Code#6]
您已经侵犯了我的版权，望能迅速进行删除。

**Comment by yltx** [comment]
我给您3天时间。3天之后，我将会提起DMCA takedown请求并向Microsoft提出删除您的插件的请求，相信我，我的请求会被批准的。

**Comment by zxp2019** [comment]
zc!

**Comment by Miller-ZYF** [comment]
资瓷！

**Comment by tim1103** [comment]
@yltx 该提交DMCA了😂

**Comment by zxp2019** [comment]
> 
> 
> @yltx 该提交DMCA了😂

附议，@yltx

**Comment by Miller-Luogu** [comment]
@yltx  DMCA准备

**Comment by chuang-zhi** [comment]
你可以尝试一下。请问我抄了什么呢·？侵犯您什么版权了呢？你说我抄您编译后的的js代码，您倒是拿出来看看啊？没有证据就在这里……诶……

**Comment by chuang-zhi** [comment]
就算我抄了，您一开始的开源也是MIT吧？

**Comment by yltx** [comment]
有趣。
我发布这个issue是建立在我希望能以协商的方式解决这个问题的基础上，而显然如果协商成功了您干了什么自己心里清楚，自己进行删除，当然不需要证据；而协商失败了我在这里提供证据也没有用：只用用DMCA takedown的强制手段来迫使您删除。故，我在这个issue中没有必要给出证据。希望您想清楚，这个issue是个协商的尝试，而不是我来找您对线。既然您拒绝承认抄袭行为，那么我的解决方法很简单：提起DMCA takedown申请。
关于MIT协议，或许我和您对于“发布”这一权利的理解有些不同：我认为的发布应当是以vscode-luogu的名义进行发布，而不是冠以Luogu On VSCode的名义，以vscode-luogu的实质发布。

------

关于DMCA takedown的申请为何咕到现在：DMCA takedown申请有关于语言和格式上的严格要求，而且要求全文用英语写成，所以我并不愿意使用这种方式，而希望能以协商的方式解决问题，这也就是我为何发布这个issue。所以，我事实上是从4天前开始准备这个东西，而纯英文的写作是需要时间的，所以DMCA takedown的申请一直咕到了现在。

**Comment by zxp2019** [comment]
@zzsmallfang 有问题直说 背地里阴恻恻点个踩又是什么意思

**Comment by YanWQ-monad** [comment]
> 就算我抄了，您一开始的开源也是MIT吧？

看了一下 LICENSE，不错，居然按照 MIT 的约定保留了原仓库的 LICENSE。👍👍👍

**Comment by zxp2019** [comment]
这个仓库既然写的是yltx的版权 那么为什么要挂在 chuang-zhi 的名下？

**Comment by zxp2019** [comment]
如果要修改，为什么不能到原仓库提交PR？

**Comment by zxp2019** [comment]
（原谅本人萌新  求大佬赐教）
